DROP TABLE IF EXISTS USUARIO CASCADE;	
CREATE TABLE USUARIO(Id SERIAL PRIMARY KEY,
					Nome VARCHAR(500) NOT NULL,
					Endereco VARCHAR(1000) NOT NULL,
    				Email VARCHAR(500) NOT NULL,
    				Login VARCHAR(100) UNIQUE NOT NULL,
    				Senha VARCHAR(16) NOT NULL,
    				Administrador BOOLEAN NOT NULL
					);
					
DROP TABLE IF EXISTS CATEGORIA CASCADE;					
CREATE TABLE CATEGORIA(Id SERIAL PRIMARY KEY,
					   Descricao VARCHAR(2000) NOT NULL
					  );

DROP TABLE IF EXISTS PRODUTO CASCADE;
CREATE TABLE PRODUTO(Id SERIAL PRIMARY KEY,
					Descricao VARCHAR(2000) NOT NULL,
    				Preco NUMERIC(15,2)  NOT NULL,
    				Foto VARCHAR(2000),
    				Quantidade INTEGER NOT NULL,
					Categoria_Id INTEGER NOT NULL REFERENCES CATEGORIA(Id) ON DELETE CASCADE
					);
					
DROP TABLE IF EXISTS VENDA CASCADE;
CREATE TABLE VENDA(Id SERIAL PRIMARY KEY,
					Data_Hora VARCHAR(2000) NOT NULL,
    				Preco TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    				Usuario_Id INTEGER NOT NULL REFERENCES USUARIO(Id) ON DELETE CASCADE
					);
					
DROP TABLE IF EXISTS VENDA_PRODUTO CASCADE;
CREATE TABLE VENDA_PRODUTO(
	Venda_Id INTEGER NOT NULL REFERENCES VENDA(Id) ON DELETE CASCADE,
	Produto_Id INTEGER NOT NULL REFERENCES PRODUTO(Id) ON DELETE CASCADE,
	Quantidade INTEGER NOT NULL,
	PRIMARY KEY (Venda_Id, Produto_Id)
);
