version: '3.7'
services:
  ecommerce-database:
    container_name: ecommerce-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: ecommerce
    ports:
      - '5433:5432'
    volumes:
      - ./Pet.Commerce.Infra/Scripts/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./Pet.Commerce.Infra/Scripts/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  pet-api:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ConnectionStrings__ConnectionString=User ID=user;Password=user123;Server=ecommerce-database;Port=5432;Database=ecommerce;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ecommerce-database


      